from app.utils.firebase import db
from flask import jsonify
import secrets

def add_word_service(chinWord, pinyin, meaning, lvl):
    data = {
        "word": chinWord,
        "pinyin": pinyin,
        "meaning": meaning,
        "lvl": lvl
    }

    try:
        custom_id = secrets.token_urlsafe(6) # shorten the document id b/c the firestore autogenerated one is really long
        db.collection('wordbank').document(custom_id).set(data) # set the document id in firestore to be the customid

        return jsonify({
            "status": "success",
            "msg": f'{chinWord} added to database'
        })

    except Exception as error:
        return jsonify(error.message)
    
def get_words_service():
    docs = db.collection('wordbank').stream()
    words = []

    for doc in docs:
        doc_as_dict = doc.to_dict()
        doc_as_dict['id'] = doc.id
        words.append(doc_as_dict)

    return jsonify(words)

def delete_word_service(doc_id):
    try:
        db.collection('wordbank').document(doc_id).delete()
        return jsonify({
            "status": "success",
            "msg": "word deleted"
        })
    except Exception as error:
        return jsonify(error.message)